### ISSUE TITLE
What's with the emojis in commit messages?

### ISSUE THREAD

**Issue by alphaolomi** [BaharaJr/js-starter-kit#1]
Is it some sort of standard?

**Comment by BaharaJr** [comment]
Hahaha yooh @alphaolomi  I just found them out and was so excited to use them

**Comment by alphaolomi** [comment]
i think i will stick to something like https://commitizen.github.io/cz-cli/

**Comment by BaharaJr** [comment]
You can also use them in a CLI https://gitmoji.carloscuesta.me/
